# Trabalho 01 - Aprendizado de máquina
Aluno: Pedro Tashima

## Instala e importa pacotes

In [117]:
!python3 -m pip install -r ../requirements.txt

Requirement already satisfied: numpy~=2.3.2 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from -r ../requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: pandas~=2.3.2 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from -r ../requirements.txt (line 2)) (2.3.2)
Requirement already satisfied: statsmodels==0.14.5 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from -r ../requirements.txt (line 3)) (0.14.5)
Requirement already satisfied: scikit-learn==1.7.1 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from -r ../requirements.txt (line 4)) (1.7.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from statsmodels==0.14.5->-r ../requirements.txt (line 3)) (1.16.1)
Requirement already satisfied: patsy>=0.5.6 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from statsmodels==0.14.5->-r ../requirements.txt (line 3)) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from statsmodels==0.14.5->-r ../requirements.txt (line 3)) (25.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from scikit-learn==1.7.1->-r ../requirements.txt (line 4)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from scikit-learn==1.7.1->-r ../requirements.txt (line 4)) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from pandas~=2.3.2->-r ../requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from pandas~=2.3.2->-r ../requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from pandas~=2.3.2->-r ../requirements.txt (line 2)) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/pedro/code/tashima42/disciplinas/ciencia-de-dados/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas~=2.3.2->-r ../requirements.txt (line 2)) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [118]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

## Lê dados

In [119]:
df=pd.read_csv('../data/imoveis_treino.csv', sep=";", index_col="Índice")
df_test=pd.read_csv('../data/imoveis_teste.csv', sep=";", index_col="Índice")

dic_rename = {"N° de Quartos": "n_quartos", "N de Quartos": "n_quartos"}

LE = LabelEncoder()
LE_tipo = LabelEncoder()

df = df.rename(columns=dic_rename)
df.Bairro = pd.Categorical(df.Bairro)
df['bairro_code'] = LE.fit_transform(df['Bairro'])
df['tipo_code'] = LE_tipo.fit_transform(df['Tipo'])


df_test = df_test.rename(columns=dic_rename)
df_test.Bairro = pd.Categorical(df_test.Bairro)
df_test['bairro_code'] = LE.fit_transform(df_test['Bairro'])
df_test['tipo_code'] = LE_tipo.fit_transform(df_test['Tipo'])

df.head()

,Bairro,Tamanho,n_quartos,Tipo,Vagas de Garagem,Valor de Venda,bairro_code,tipo_code
Índice,,,,,,,,
1,Batel,220,4,Casa,4,3168000,1,1
2,Batel,140,3,Apartamento,2,1680000,1,0
3,Batel,180,3,Sobrado,3,2376000,1,2
4,Batel,95,2,Apartamento,1,1140000,1,0
5,Batel,300,5,Casa,4,4320000,1,1

## Análise exploratória

In [120]:
print("valores nulos: ")
print(df.isna().sum())
print("--------------------------------------")
print("informacoes gerais: ")
print(df.info())
print("--------------------------------------")
print(df["Bairro"].value_counts())
print("--------------------------------------")
print(df["Tipo"].value_counts())
print(df["Vagas de Garagem"].value_counts())

valores nulos:
Bairro              0
Tamanho             0
n_quartos           0
Tipo                0
Vagas de Garagem    0
Valor de Venda      0
bairro_code         0
tipo_code           0
dtype: int64
--------------------------------------
informacoes gerais:
<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 1 to 220
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Bairro            220 non-null    category
 1   Tamanho           220 non-null    int64
 2   n_quartos         220 non-null    int64
 3   Tipo              220 non-null    object
 4   Vagas de Garagem  220 non-null    int64
 5   Valor de Venda    220 non-null    int64
 6   bairro_code       220 non-null    int64
 7   tipo_code         220 non-null    int64
dtypes: category(1), int64(6), object(1)
memory usage: 14.3+ KB
None
--------------------------------------
Bairro
Ahú               20
Batel             20
Bigorrilho        20
CIC               20
Cabral            20
Campo Comprido    20
Centro            20
Juvevê            20
Pilarzinho        20
Portão            20
Água Verde        20
Name: count, dtype: int64
--------------------------------------
Tipo
Apartamento    97
Casa           77
Sobrado        46
Name: count, dtype: int64
Vagas de Garagem
2    89
1    66
3    41
4    24
Name: count, dtype: int64

In [121]:
df.describe()

,Tamanho,n_quartos,Vagas de Garagem,Valor de Venda,bairro_code,tipo_code
count,220.000000,220.000000,220.000000,2.200000e+02,220.000000,220.000000
mean,129.568182,2.772727,2.104545,1.240482e+06,5.000000,0.768182
std,56.437219,0.918198,0.957059,7.568069e+05,3.169489,0.773940
min,55.000000,1.000000,1.000000,3.300000e+05,0.000000,0.000000
25%,84.250000,2.000000,1.000000,6.632000e+05,2.000000,0.000000
50%,115.000000,3.000000,2.000000,1.014000e+06,5.000000,1.000000
75%,170.000000,3.000000,3.000000,1.612125e+06,8.000000,1.000000
max,300.000000,5.000000,4.000000,4.320000e+06,10.000000,2.000000

In [122]:
df[["Tamanho", "n_quartos", "Vagas de Garagem", "bairro_code", "tipo_code"]].corr()

,Tamanho,n_quartos,Vagas de Garagem,bairro_code,tipo_code
Tamanho,1.000000,0.896526,0.920613,-0.119773,0.458615
n_quartos,0.896526,1.000000,0.848152,-0.061192,0.561654
Vagas de Garagem,0.920613,0.848152,1.000000,-0.070750,0.384255
bairro_code,-0.119773,-0.061192,-0.070750,1.000000,0.022338
tipo_code,0.458615,0.561654,0.384255,0.022338,1.000000

## Divide o dataset

In [123]:
X = df[["Tamanho", "n_quartos", "Vagas de Garagem", "bairro_code", "tipo_code"]]
y = df[["Valor de Venda"]]

X_test = df_test[["Tamanho", "n_quartos", "Vagas de Garagem", "bairro_code", "tipo_code"]]
y_test = df_test[["Valor de Venda"]]
X_test.head()

        Tamanho  n_quartos  Vagas de Garagem  bairro_code  tipo_code
Índice
1            75          2                 1            1          0
2           105          3                 2            1          0
3           150          3                 3            1          2
4           120          3                 2            1          2
5           240          4                 4            1          1

In [124]:
lm=LinearRegression()
lm.fit(X,y)

print(lm.intercept_,lm.coef_)

[-91183.44341275] [[  16016.31453393 -107066.28803346 -120187.80943908  -32985.21064286
   -37500.08911916]]

In [128]:
y_pred = lm.predict(X_test)
y_pred

array([[ 742734.55048346],
       [ 995969.88902894],
       [1521516.05537858],
       [1161214.42879963],
       [2773230.35507927],
       [2092602.43782164],
       [ 773814.59797633],
       [ 802821.53304674],
       [1368473.93616578],
       [1768881.79951414],
       [2219780.37251812],
       [3140653.00778476],
       [ 432709.08488875],
       [ 785068.0046353 ],
       [ 963303.16494247],
       [1363711.02829082],
       [2081839.03466761],
       [2094829.65520409],
       [ 595729.97495307],
       [ 816932.68443069],
       [1062258.79687105],
       [1382585.08754973],
       [2073728.37856273],
       [2514111.57781135],
       [ 722622.90382043],
       [1055939.81503559],
       [1354362.78478183],
       [1647704.36009673],
       [1912327.64581928],
       [2485889.27504345],
       [ 525949.22736738],
       [ 597957.19233551],
       [ 624102.81500488],
       [1024510.67835323],
       [1422312.39405134],
       [1835710.87793616],
       [ 412597.43822573],
       [ 609841.12633702],
       [ 871183.55331132],
       [1108402.57732287],
       [1562326.84432432],
       [1847594.81193767],
       [ 526901.80894237],
       [ 635990.31668246],
       [ 737169.59831741],
       [1217659.03433543],
       [1535379.17736387],
       [1948777.6612487 ],
       [ 402581.61897087],
       [ 591751.69938062],
       [ 829135.10498859],
       [1029273.58622819],
       [1507156.87459597],
       [1968604.3020826 ],
       [ 527569.38468825],
       [ 420503.09665479],
       [ 986155.49977383],
       [1079227.69297998],
       [1276890.92743848],
       [1530126.26598397],
       [ 383707.55971196],
       [ 744009.1862909 ],
       [ 722105.86535847],
       [1058448.47057108],
       [1312103.35546378],
       [1725501.83934861]])

In [126]:
print("Erro quadrático Médio: %.2f" % mean_squared_error(y_test, y_pred))
print("R2: %.4f" % r2_score(y_test, y_pred))

Erro quadrático Médio: 43851850780.74
R2: 0.9048